### ISSUE TITLE
Benchmark against object-path

### ISSUE THREAD

**Issue by d4nyll** [jonschlinkert/get-value#11]
A similar package to `get-value` is [`object-path`](https://www.npmjs.com/package/object-path), which has 2,163,767 downloads in the last month.

I think it's worth adding this package to the benchmark alongside `dot-prop`.

What do you think?

**Comment by jonschlinkert** [comment]
done! https://github.com/jonschlinkert/get-value#benchmarks

**Comment by d4nyll** [comment]
Awesome! Thanks for the quick response @jonschlinkert!
