### ISSUE TITLE
Please pre-compiled before publish

### ISSUE THREAD

**Issue by McLemore** [jonschlinkert/get-value#13]
"get-value" is great. I'm using get-value@3.0.1, but it not pre-compiled to es5 that cause break in older browser and uglify-webpack-plugin, can you fix it, pre-compiled es6 to es5 before publish. thx a lot.
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by doowb** [comment]
You should set up your bundler to precompile this package if you need to target older browsers. Also, the only es6 type of feature in this package is `const` or `let`. You could also try finding out if the webpack plugin supports using a newer version of uglify (there's one that will work with es6).

**Comment by McLemore** [comment]
@doowb Thanks. I get it.
