### ISSUE TITLE
how to get a path of a key?

### ISSUE THREAD

**Issue by CavalcanteLeo** [jonschlinkert/get-value#22]
how to get a path of a key?
not the value.

I'm iterating all object keys, and store some important keys in another object, since my loop is in an important key, i want to store it, but how can i convert to a path?

```javascript
const obj = {
   foo: {
      bar: true
   }
}
```

i want to return `'foo.bar'`

**Comment by Slapbox** [comment]
Seems outside the scope of this project.

**Comment by doowb** [comment]
Hi @CavalcanteLeo, you can use [stringify-keys](https://github.com/doowb/stringify-keys) to get an array of property paths to the values. You can do this before your loop, then loop over those paths.
