### ISSUE TITLE
Question - any significant differences between this library and lodash's _.get() ?

### ISSUE THREAD

**Issue by Slapbox** [jonschlinkert/get-value#24]
They seem interchangeable at a glance. Is there any significant difference?

**Comment by doowb** [comment]
You should be able to replace `_.get()` with `get-value`.
I'm haven't looked at all of options available to `_.get()`, so there might be some differences outside the default usage.

If you experience an unexpected use case, please feel free to open an issue with some example code, what you expected, and what is actually happening.
