### ISSUE TITLE
Open to PR with `get(...default='default')`?

### ISSUE THREAD

**Issue by rmharrison** [jonschlinkert/get-value#8]
Same behavior as `get()`, but returns the default value instead of undefined?

For example...
```js
> var obj = {a: {b: 'c'}}

> get(obj, 'a.b')
'c'

> get(obj, 'a.b.c.d.e')
undefined

> get(obj, 'a.b.c.d.e', default='default')
'default'
```

**Comment by jonschlinkert** [comment]
Hi @rmharrison, I think it would be better to use another library for this, so we can keep each function focused on a single responsibility. for example:

```js
> var koalas = require('koalas')
> var get = require('get-value')
> var obj = {a: {b: 'c'}}
> koalas(get(obj, 'a.b.c.d.e'), 'default')
'default'
```

**Comment by rmharrison** [comment]
Thanks for the prompt feedback.

Used [npm:object-path](https://www.npmjs.com/package/object-path), which is a heavier-weight alternative to the `get-value` suite.
