### ISSUE TITLE
npmjs package does not include readme

### ISSUE THREAD

**Issue by arve0** [jonschlinkert/get-value#9]

**Comment by jonschlinkert** [comment]
Strange, doesn't NPM usually include it by default? Or do I need to add it to the `files` array in package.json to explicitly tell NPM to include the readme?

**Comment by arve0** [comment]
[The manual](https://docs.npmjs.com/files/package.json#files) states:

> Certain files are always included, regardless of settings:

README is in that list.

**Comment by arve0** [comment]
Use some build process for README, which makes it disappear when you do `npm publish`?

**Comment by jonschlinkert** [comment]
> Use some build process for README, which makes it disappear when you do npm publish?

What does this mean?

**Comment by arve0** [comment]
Long shot: Do you use some build process, that deletes README.md locally, so that `npm publish` cannot find `README.md` by some race condition?

**Comment by jonschlinkert** [comment]
no, I see what you mean. There is always a README.md when doing `npm publish`. good thinking though.

**Comment by doowb** [comment]
The README is there on npm now. It was probably a bug on npm's side when publishing at once point. I have seen other packages that this has happened to and it's usually fixed when the next version is published.
